version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      # - ${SERVER_PORT}:${SERVER_PORT}
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongodb
    #   - redis
    #   - postgres
  mongodb:
    image: mongo:5.0
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    networks:
      - webnet
  # redis:
  #   container_name: redis
  #   image: redis:5
  #   networks:
  #     - webnet
  # postgres:
  #   container_name: postgres
  #   image: postgres:12
  #   networks:
  #     - webnet
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_DATABASE_NAME}
  #     PG_DATA: /var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata: